2023-04-29 23:18:40,768 | ERROR | listdir: path should be string, bytes, os.PathLike or None, not dict
Traceback (most recent call last):
  File "D:\Background\conda\envs\li_env\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Background\conda\envs\li_env\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\Project\Money\flaskTemplate\blueprints\fileController.py", line 12, in get_origin_list
    data = dfs_files(DATA_ADDR)
  File "D:\Project\Money\flaskTemplate\utils\file_utils.py", line 13, in dfs_files
    for item in os.listdir(current_path):
TypeError: listdir: path should be string, bytes, os.PathLike or None, not dict
2023-04-29 23:21:12,994 | ERROR | Object of type resDTO is not JSON serializable
Traceback (most recent call last):
  File "D:\Background\conda\envs\li_env\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Background\conda\envs\li_env\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\Project\Money\flaskTemplate\blueprints\fileController.py", line 13, in get_origin_list
    return jsonify(resDTO(200, "请求成功", [2,3,4]))
  File "D:\Background\conda\envs\li_env\lib\site-packages\flask\json\__init__.py", line 342, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "D:\Background\conda\envs\li_env\lib\site-packages\flask\json\provider.py", line 309, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=mimetype
  File "D:\Background\conda\envs\li_env\lib\site-packages\flask\json\provider.py", line 230, in dumps
    return json.dumps(obj, **kwargs)
  File "D:\Background\conda\envs\li_env\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "D:\Background\conda\envs\li_env\lib\json\encoder.py", line 201, in encode
    chunks = list(chunks)
  File "D:\Background\conda\envs\li_env\lib\json\encoder.py", line 438, in _iterencode
    o = _default(o)
  File "D:\Background\conda\envs\li_env\lib\site-packages\flask\json\provider.py", line 122, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type resDTO is not JSON serializable
2023-04-29 23:28:55,138 | ERROR | listdir: path should be string, bytes, os.PathLike or None, not dict
Traceback (most recent call last):
  File "D:\Background\conda\envs\li_env\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Background\conda\envs\li_env\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\Project\Money\flaskTemplate\blueprints\fileController.py", line 12, in get_origin_list
    data = dfs_files(DATA_ADDR)
  File "D:\Project\Money\flaskTemplate\utils\file_utils.py", line 13, in dfs_files
    for item in os.listdir(current_path):
TypeError: listdir: path should be string, bytes, os.PathLike or None, not dict
2023-04-29 23:30:21,949 | ERROR | listdir: path should be string, bytes, os.PathLike or None, not dict
Traceback (most recent call last):
  File "D:\Background\conda\envs\li_env\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Background\conda\envs\li_env\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\Project\Money\flaskTemplate\blueprints\fileController.py", line 12, in get_origin_list
    data = dfs_files(DATA_ADDR)
  File "D:\Project\Money\flaskTemplate\utils\file_utils.py", line 13, in dfs_files
    s = os.listdir(current_path)
TypeError: listdir: path should be string, bytes, os.PathLike or None, not dict
2023-04-30 17:49:57,865 | ERROR | 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
Traceback (most recent call last):
  File "D:\Background\conda\envs\flask365\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Background\conda\envs\flask365\lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    return self.finalize_request(rv)
  File "D:\Background\conda\envs\flask365\lib\site-packages\flask\app.py", line 1538, in finalize_request
    response = self.make_response(rv)
  File "D:\Background\conda\envs\flask365\lib\site-packages\flask\app.py", line 1716, in make_response
    rv = jsonify(rv)
  File "D:\Background\conda\envs\flask365\lib\site-packages\flask\json\__init__.py", line 361, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "D:\Background\conda\envs\flask365\lib\site-packages\flask\json\__init__.py", line 139, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "D:\Background\conda\envs\flask365\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "D:\Background\conda\envs\flask365\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "D:\Background\conda\envs\flask365\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "D:\Background\conda\envs\flask365\lib\site-packages\flask\json\__init__.py", line 57, in default
    return super().default(o)
  File "D:\Background\conda\envs\flask365\lib\json\encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Record' is not JSON serializable
2023-04-30 17:54:05,856 | ERROR | 'Record' object has no attribute 'uuid'
Traceback (most recent call last):
  File "D:\Background\conda\envs\flask365\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Background\conda\envs\flask365\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\Project\Money\flaskTemplate\blueprints\fileController.py", line 43, in get_progress
    "uuid": item.uuid,
AttributeError: 'Record' object has no attribute 'uuid'
2023-04-30 18:06:39,967 | ERROR | 'NoneType' object has no attribute 'ids'
Traceback (most recent call last):
  File "D:\Background\conda\envs\flask365\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Background\conda\envs\flask365\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\Project\Money\flaskTemplate\blueprints\fileController.py", line 59, in download_files
    file_name = record.ids + ".csv"
AttributeError: 'NoneType' object has no attribute 'ids'
2023-04-30 18:07:13,049 | ERROR | 'NoneType' object has no attribute 'ids'
Traceback (most recent call last):
  File "D:\Background\conda\envs\flask365\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Background\conda\envs\flask365\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\Project\Money\flaskTemplate\blueprints\fileController.py", line 59, in download_files
    file_name = record.ids + ".csv"
AttributeError: 'NoneType' object has no attribute 'ids'
2023-04-30 18:08:23,081 | ERROR | 'ImmutableMultiDict' object has no attribute 'get_json'
Traceback (most recent call last):
  File "D:\Background\conda\envs\flask365\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Background\conda\envs\flask365\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\Project\Money\flaskTemplate\blueprints\fileController.py", line 57, in download_files
    uuid = data.get_json("uuid")
AttributeError: 'ImmutableMultiDict' object has no attribute 'get_json'
